const assert = require('node:assert/strict');
const Module = require('node:module');
const test = require('node:test');

function loadRouter(query) {
  const routePath = require.resolve('./cases');
  const originalLoad = Module._load;

  delete require.cache[routePath];
  Module._load = function load(request, parent, isMain) {
    if (request === '../db') {
      return { query };
    }
    return originalLoad.call(this, request, parent, isMain);
  };

  try {
    return require('./cases');
  } finally {
    Module._load = originalLoad;
    delete require.cache[routePath];
  }
}

function routeHandler(router, method, path) {
  const layer = router.stack.find(
    (candidate) => candidate.route?.path === path && candidate.route.methods[method]
  );

  assert.ok(layer, `${method.toUpperCase()} ${path} route must exist`);
  return layer.route.stack.find((candidate) => candidate.method === method).handle;
}

function responseRecorder() {
  return {
    statusCode: 200,
    body: undefined,
    status(code) {
      this.statusCode = code;
      return this;
    },
    json(body) {
      this.body = body;
      return this;
    },
  };
}

test('the cases router has a loadable database client', () => {
  const db = require('../db');
  assert.equal(typeof db.query, 'function');
});

test('creating a case lets PostgreSQL generate the serial id', async () => {
  const calls = [];
  const query = async (sql, params) => {
    calls.push({ sql, params });
    return { rows: [{ id: 41 }] };
  };
  const router = loadRouter(query);
  const handler = routeHandler(router, 'post', '/cases');
  const res = responseRecorder();
  const content = { steps: [{ action: 'tap' }] };

  await handler(
    {
      body: {
        suite_id: 7,
        name: 'checkout',
        description: 'critical flow',
        type: 'web',
        content,
      },
      user: { id: 'author' },
    },
    res
  );

  assert.equal(res.statusCode, 201);
  assert.equal(calls.length, 1);
  assert.doesNotMatch(calls[0].sql, /INSERT INTO test_case\s*\(\s*id\s*,/i);
  assert.deepEqual(calls[0].params, [
    7,
    'checkout',
    'critical flow',
    'web',
    JSON.stringify(content),
    'author',
  ]);
  assert.equal(res.body.data.id, 41);
});

test('running a case returns the serial execution id generated by PostgreSQL', async () => {
  const calls = [];
  const query = async (sql, params) => {
    calls.push({ sql, params });
    if (/FROM test_case/i.test(sql)) {
      return { rows: [{ id: 12, suite_id: 7 }] };
    }
    if (/FROM test_suite/i.test(sql)) {
      return { rows: [{ id: 7 }] };
    }
    return { rows: [{ id: 93 }] };
  };
  const router = loadRouter(query);
  const handler = routeHandler(router, 'post', '/cases/:id/run');
  const res = responseRecorder();

  await handler({ params: { id: '12' }, body: { device_id: 5 } }, res);

  assert.equal(calls.length, 3);
  assert.doesNotMatch(calls[2].sql, /INSERT INTO test_execution\s*\(\s*id\s*,/i);
  assert.match(calls[2].sql, /RETURNING id/i);
  assert.deepEqual(calls[2].params, [7, 5]);
  assert.deepEqual(res.body.data, { execution_id: 93 });
});
