const assert = require('node:assert/strict');
const Module = require('node:module');
const test = require('node:test');

function loadRouterWithDb(db) {
  const casesPath = require.resolve('./cases');
  delete require.cache[casesPath];

  const originalLoad = Module._load;
  Module._load = function patchedLoad(request, parent, isMain) {
    if (request === '../db' && parent?.filename === casesPath) {
      return db;
    }
    return originalLoad.call(this, request, parent, isMain);
  };

  try {
    return require('./cases');
  } finally {
    Module._load = originalLoad;
  }
}

function routeHandler(router, method, path) {
  const layer = router.stack.find((entry) => entry.route?.path === path && entry.route.methods[method]);
  assert.ok(layer, `Expected route ${method.toUpperCase()} ${path} to exist`);
  return layer.route.stack[0].handle;
}

function createJsonResponse() {
  return {
    statusCode: 200,
    body: undefined,
    status(code) {
      this.statusCode = code;
      return this;
    },
    json(payload) {
      this.body = payload;
      return this;
    },
  };
}

test('POST /cases lets PostgreSQL generate the SERIAL case id', async () => {
  let capturedQuery;
  const db = {
    async query(sql, params) {
      capturedQuery = { sql, params };
      return { rows: [{ id: 101, name: 'checkout smoke' }] };
    },
  };
  const router = loadRouterWithDb(db);
  const handler = routeHandler(router, 'post', '/cases');
  const res = createJsonResponse();

  await handler(
    {
      body: {
        suite_id: 7,
        name: 'checkout smoke',
        description: 'critical checkout path',
        type: 'web',
        content: { steps: [] },
      },
      user: { id: 42 },
    },
    res
  );

  assert.equal(res.statusCode, 201);
  assert.match(capturedQuery.sql, /INSERT INTO test_case \(suite_id, name, description, type, content, created_by, created_at, updated_at\)/);
  assert.deepEqual(capturedQuery.params, [
    7,
    'checkout smoke',
    'critical checkout path',
    'web',
    JSON.stringify({ steps: [] }),
    42,
  ]);
});

test('POST /cases/:id/run returns the SERIAL execution id generated by PostgreSQL', async () => {
  const queries = [];
  const db = {
    async query(sql, params) {
      queries.push({ sql, params });

      if (sql.includes('FROM test_case')) {
        return { rows: [{ id: 101, suite_id: 7, name: 'checkout smoke' }] };
      }
      if (sql.includes('FROM test_suite')) {
        return { rows: [{ id: 7, name: 'smoke' }] };
      }
      if (sql.includes('INSERT INTO test_execution')) {
        return { rows: [{ id: 555 }] };
      }

      throw new Error(`Unexpected SQL: ${sql}`);
    },
  };
  const router = loadRouterWithDb(db);
  const handler = routeHandler(router, 'post', '/cases/:id/run');
  const res = createJsonResponse();

  await handler(
    {
      params: { id: '101' },
      body: { device_id: 3 },
    },
    res
  );

  const executionInsert = queries.find((query) => query.sql.includes('INSERT INTO test_execution'));

  assert.equal(res.statusCode, 200);
  assert.match(executionInsert.sql, /INSERT INTO test_execution \(suite_id, device_id, status, start_time, created_at\)/);
  assert.deepEqual(executionInsert.params, [7, 3]);
  assert.deepEqual(res.body.data, { execution_id: 555 });
});
